sudo: false
language: node_js
node_js:
  - 10.1.0

cache:
  directories:
    - node_modules

before-install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential g++

script:
  - npm test

notifications:
  email: false

before_deploy:
  - npm run build && cp -r public/* dist

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: main
  verbose: true
